name: Build

on:
  push:
    paths:
      - "bookmarker-api/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "bookmarker-api/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Display project structure
        run: ls -R

      - name: Build with Maven
        run: ./mvnw -ntp verify

#correct Mains branch to main
      - if: ${{ github.ref == 'refs/heads/Mains' }}
        name: Build and Publish Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/bookmarker-api
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
